---
title: "test"
author: "alejandro"
date: "2024-01-29"
output: 
  html_document: 
    toc: yes
    highlight: haddock
    theme: yeti
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Section header

This is the first section. I can make words **bold**

## This is a subsection

### This is a subsubsection

We make italics like *this*

```{r}
#| echo: false

important_number <- 3 + 17 * 12 / 2

````

This is text and this is my number: `r important_number`.


```{r}

tonic_syllable_dur <- 156
atonic_syllable_dur <- 202

dur_diff <- tonic_syllable_dur - atonic_syllable_dur

tonic_syllable_int <- 78.83
atonic_syllable_int <- 69.91

int_diff <- tonic_syllable_int - atonic_syllable_int

```


```{r}
library(tidyverse)

```

```{r}
dat <- read_csv("stress.csv")
```

```{r}

dat |>
  pivot_longer(cols = f0:dur, names_to = "measure", values_to = "val") |>
  ggplot() +
  aes(x = measure, y = val, fill= vowel) +
  geom_boxplot()

dat |>
  pivot_longer(cols = f0:dur, names_to = "measure", values_to = "val") |>
  group_by(vowel, measure) |>
  summarise(avg = mean(val)) |>
  pivot_wider(names_from = "vowel", values_from = "avg")


```

```{r}

for (i in 1:10) {
  print(i)
}

print(i)

for (i in 1:10) {
  print(i +1)
}

for (i in 1:10) {
  print(i*2)
}

for (i in 1:10) {
  print(i^2)
}


x <- 1:10

for (i in x) {
  print(i)
}


```


```{r}

glimpse(dat)
dim(dat)
str(dat)
summary(dat)
head(dat)


dat %>%
  select(id, vowel)

dat %>%
  filter(vowel == "e")

dat %>%
  filter(vowel != "e")

dat %>%
  filter(f0 >= 150)

dat %>%
  filter(f0 >= 150, int >= 60)


```










